### ISSUE TITLE
[CSS] Header : Flex Container의 Flex item의 간격을 균등하게 나누는 방법

### ISSUE THREAD

**Issue by yksvSG** [yksvSG/apple-ipad#2]
### 학습 항목
> - [X] css
> - [ ] js
> - [ ] react
> - [ ] typescript

### 학습한 내용
<img width="1084" alt="스크린샷 2023-01-05 오후 7 51 20" src="https://user-images.githubusercontent.com/93868114/210763272-a0e6aa70-0782-432c-94a7-ea4a5decf9c0.png">

- 위 캡쳐와 같이 헤더의 구성요소들의 간격을 균등하게 나누는 방법을 학습했습니다.
1.  flex item의 진행 축 정렬과 간격을 제어하기 위해  justify-content를 flex container에 추가합니다.
2. 헤더의 구성요소들은 각각 여분의 공간을 가지고 있으므로, flex item 사이의 공간을 제어할 수 있는 <br/> space-between, space-around 값을 고려합니다
3. space-between은 주축의 시작과 끝에 첫번째 item과 마지막 item을 배치하고 그 안에 공간을 균등하게 분배합니다.
4. space-around 는 각 item 마다 균등하게 간격을 분배합니다.

-  justify-content: space-around 를 적용한 요소 내의 a 태그의 height를 flex item의 height로 맞추는 방법입니다.
https://codepen.io/yksvSG/pen/GRBNRpr

<img width="973" alt="스크린샷 2023-01-05 오후 8 22 58" src="https://user-images.githubusercontent.com/93868114/210769018-8e48edcc-95eb-4cce-9b0e-376340cfcda0.png">

```html
<div class="container">
  <div class="item">
    <a href="">1</a></div>
  <div class="item"><a href="">2</a></div>
  <div class="item"><a href="">3</a></div>
  <div class="item"><a href="">4</a></div>
</div>
```
```css
.container {
  height: 150px;
  border: 4px solid;
  display: flex;
  justify-content: space-around;
}

.item {
  border: 4px solid red;
}

.item a {
  padding: 0 10px;
  border: 4px solid green;
}
```
1. flex item은 기본적으로 교차축으로 최대한 늘어나는 특성을 가집니다.
2. 이 특성을 사용하여 a태그의 height를 교차축으로 늘려주면 됩니다.
<img width="973" alt="스크린샷 2023-01-05 오후 8 23 07" src="https://user-images.githubusercontent.com/93868114/210769072-63f5c630-17f2-4614-915b-4ac6bd19ae7b.png">

```css
.item {
  border: 4px solid red;
  display: flex;
}

.item a {
  padding: 0 10px;
  border: 4px solid green;
}
```

## 적용하기
<img width="1431" alt="스크린샷 2023-01-05 오후 8 34 43" src="https://user-images.githubusercontent.com/93868114/210771181-92b33328-fcf9-4d78-819e-e130d81824d7.png">
