### ISSUE TITLE
[CSS] Display 와 Visivility 속성의 차이

### ISSUE THREAD

**Issue by yksvSG** [yksvSG/apple-ipad#4]
### 학습 항목
> - [X] css
> - [ ] js
> - [ ] react
> - [ ] typescript

### 학습한 내용
>  #### [CSS] Display 와 Visivility 속성을 사용해 특정 요소를 사라지게 만드는 방법
>
> 1. Display 와 Visivility 의 가장 큰 차이점은 **레이아웃에 영향을 주느냐** 입니다.
>  여기서 "레이아웃에 영향을 준다는 것"은 바로, 속성이 적용된 요소의 공간을 의미합니다.
>  Display 와 Visivility  은 모두 속성이 적용된 요소를 보이지 않게 합니다.
>
>  2. **Visivility** 속성은 해당 요소의 영역(공간)이 화면에서 노출되지 않을 뿐, 빈 공간으로써 레이아웃에 영향을 가지게 됩니다..
>  **Visivility** 는 요소에서 의해 생성된 박스를 렌더링할 것인지를 결정하는 속성입니다.
>  **Visivility** 속성은 하위 요소로 상속되며,
>  **Visivility:hidden**에 의해 보이지 않는 박스는 **display:none** 으로 지정되지 않은 한, 레이아웃에 영향을 미친닙니다.
>
>  3. 반면, **Display** 속성은 영역 자체까지 사라지게 됩니다.
>   **Display** 는 요소를 **표시하는 방법**을 지정합니다.
>  즉, 인라인 요소처럼 표현한다거, 블럭 요소처럼 표현할 때, **Display** 속성을 적용합니다.

> ## Tip
> 애니메이션을 적용할 때는 **Visivility** 속성을 적용해서 요소가 렌더링 될지 지정하면 됩니다.

## 적용하기
```css
header .basket {
  visibility: hidden;  // display:none (x)
  transition: 0.4s;
  opacity: 0;
  width: 290px;
  padding: 10px 20px;
  border: 1px solid #d2d2d2;
  border-radius: 10px;
  box-sizing: border-box;
  background-color: #fff;
  position: absolute;
  top: calc(100% + 4px);
  right: -6px;
}
header .basket.show {
  visibility: visible;  // display:block (x)
  opacity: 1;
}
```
https://webdir.tistory.com/348
https://cocobi.tistory.com/126
