### ISSUE TITLE
[CSS] 스티키 네비게이션(Sticky Navigation) 만들기

### ISSUE THREAD

**Issue by yksvSG** [yksvSG/apple-ipad#6]
### 학습 항목
> - [X] css
> - [ ] js
> - [ ] react
> - [ ] typescript

### 학습한 내용
> 1. sticky position을 활용하여, 네비게이션을 화면 상단에 고정시켜 스크롤을 진행해도 항상 노출되도록 상태를 지정합니다.
> * sticky position으로 설정된 엘리먼트는 스크롤하지 않을 때는 static position처럼 동작하다가, 
> 스크롤할 때, fixed position과 유사하게 동작합니다.
> * sticky 박스는 top, right, bottom, left 속성이 필수입니다.
> * fixed 박스는 뷰표트에 고정하지만, sticky 박스는 scroll 박스에 고정됩니다.
> * sticky 박스는 부모 박스 내부에서 공간을 차지하며, 
> sticky 박스의 부모 박스가 scroll 박스를 벗어나면, sticky 박스는 다시 일반적인 박스가 됩니다.
> * padding-top 속성으로 헤더 위에 약간의 공간을 더하고, 
> top 속성으로 동일한 오프셋(offset) 공간을 빼주면 헤더를 화면 상단에 좀 더 자연스럽게 붙일 수 있습니다.
> ex) padding-top: 32px; top: -32px;

> 2. opacity 속성과 backdrop-filter 속성을 사용하여, 네비게이션 영역 아래로 메인 영역을 살짝 비치게 설정합니다.

## 적용하기
<img width="1431" alt="스크린샷 2023-01-11 오전 9 30 54" src="https://user-images.githubusercontent.com/93868114/211690472-4cb0c924-30fb-47eb-a060-6b1a2db15be9.png">

```html
 <!-- Navigation -->
    <nav>
      <div class="inner">
        <h1>iPad</h1>
        <ul class="menu">
          <li class="active"><a href="javascript:void(0)">개요</a></li>
          <li><a href="javascript:void(0)">iPad를 선택하는 이유</a></li>
          <li><a href="javascript:void(0)">제품 사양</a></li>
        </ul>
        <button class="btn">구입하기</button>
      </div>
    </nav>
```

```css
/* Navigation */
nav {
  background-color: rgba(255, 255, 255, 0.7);
  backdrop-filter: blur(20px);
  border-bottom: 1px solid #d2d2d2;
  position: sticky;
  top: 0;
  z-index: 8;
}
nav .inner {
  max-width: 1000px;
  height: 52px;
  margin: 0 auto;
  display: flex;
  align-items: center;
}
nav h1 {
  flex-grow: 1;
  font-size: 22px;
  font-weight: 500;
}
nav .menu {
  display: flex;
  gap: 12px; 
  margin-right: 18px;
}

nav .menu li a {
  display: block;
  padding: 6px;
  font-size: 11px;
}

nav .menu li:hover a {
  color: #0071e3;
}

nav .menu li.active a {
  opacity: 0.5;
  cursor: default;
}
nav .menu li.active:hover a {
  color: #1d1d1d;
}
```
https://deeplify.dev/front-end/markup/position-sticky
