### ISSUE TITLE
[CSS] html 구조 변경 시 박스 구조 붕괴

### ISSUE THREAD

**Issue by yksvSG** [yksvSG/apple-ipad#7]
> ### 어떤 에러인가요?
> html 의 구조가 변경될 때, css 박스 구조가 붕괴되는 문제가 발생했습니다.
> <img width="954" alt="스크린샷 2023-01-11 오후 4 58 36" src="https://user-images.githubusercontent.com/93868114/211749985-fd5a73c8-c81c-4fb3-ada4-6b3807439254.png">
> <img width="773" alt="스크린샷 2023-01-11 오후 4 59 58" src="https://user-images.githubusercontent.com/93868114/211750248-f2703a97-8d22-4b2a-9611-8e7c49f8c7a3.png">
> <img width="773" alt="스크린샷 2023-01-11 오후 5 00 42" src="https://user-images.githubusercontent.com/93868114/211750397-e5bf2427-8b75-40e0-aaad-9835af209256.png">
> 
> ### 에러 핸들링 방법
> html 구조 변경에 영향을 받지 않기 위해서는,
> 1. 쌓임 순서가 필요한 박스에 position:absolute를 지정하여, 부모 요소를 기준으로 배치합니다.
> 2. transform: translate(X, Y); 속성을 사용하여, 부모 요소를 기준으로 박스를 이동 배치하면 해결됩니다.
> 
> <img width="825" alt="스크린샷 2023-01-11 오후 5 06 52" src="https://user-images.githubusercontent.com/93868114/211751563-9012842c-1bc7-46cd-bcec-7559486e01b7.png">
```html
        <div class="figures">
          <figure>
            <img
              src="./images/hero_ipad.jpg"
              alt="iPad와 Smart Keyboard 및 Apple Pencil"
            />
            <figcaption class="bgtext">
              <div class="caption-camera">
                센터 스테이지 기술이 적용된 새로운 울트라 와이드 전면 카메라
              </div>
              <div class="caption-chip">A13 BIONIC 칩 전격 탑재</div>
              <div class="caption-storage">저장 용량은 64GB부터</div>
            </figcaption>
          </figure>
        </div>
```

```css
/* Figures */
.figures {
  position: relative;
}
.figures figure,
.figures figcaption {
  top: 0;
  left: 0;
  position: absolute;
}
.figures figcaption * {
  top: 0;
  left: 0;
  position: absolute;
}

.hero figure {
  transform: translate(74px, -64px);
}
/* text-indent는 공통 설정인 .bgtext로 대체함  */
.hero figure figcaption .caption-camera {
  /* 이미지 크기만큼 width, height 적용 */
  width: 120px;
  height: 84px;
  background-image: url("../images/hero_ipad_caption_camera.png");
  transform: translate(43px, 580px);
}
.hero figure figcaption .caption-chip {
  width: 95px;
  height: 43px;
  background-image: url("../images/hero_ipad_caption_chip.png");
  transform: translate(589px, 510px);
}
.hero figure figcaption .caption-storage {
  width: 80px;
  height: 43px;
  background-image: url("../images/hero_ipad_caption_storage.png");
  transform: translate(627px, 631px);
}
.hero h2 {
  width: 738px;
  height: 145px;
  margin: 0 auto;
  background-image: url("../images/hero_headline.png");
}
```
> 
> ### 에러 핸들링을 위해 참고한 레퍼런스 링크
> 링크
